#include<iostream>
#include<string>
using namespace std;

class Car{
	int carID;
    string brand;
    string model;
    double rentalPrice;
    bool isAvailable;
    double revenue; 
    
  public:
  	Car(int id, string b, string m, double p, bool IA) 
        : carID(id), brand(b), model(m), rentalPrice(p), isAvailable(IA), revenue(0.0) {}
  	
    Car(){
        brand = "Unknown";
        model = "Generic";
        rentalPrice = 0.0;
        isAvailable = true;
        revenue = 0.0;
    }

    double ApplyDiscount(int days){
        double discount = 0.0;
        if(days >= 5 && days < 10){
            discount = rentalPrice * 0.05 * days;
        } 
         else if (days >= 10) {
            discount = rentalPrice * 0.1 * days;
        }
        return (rentalPrice * days) - discount;
    }

    void rentCar(int days){
        if(isAvailable){
            isAvailable = false;
            double finalPrice = ApplyDiscount(days);
            revenue += finalPrice;  
            cout<<"\nCar rented successfully for "<<days<<" days"<<endl;
            cout<<"Total cost after discount: "<<finalPrice<<endl;
        } 
		else{
            cout<<"Car is already rented ";
        }
    }

    void returnCar(){
        isAvailable = true;
        cout<<"\nCar returned successfully ";
    }

    void ShowInfo(){
        cout<<"\nCar Details: "<<endl;
        cout<<"Car ID: "<<carID<<endl;
        cout<<"Brand: "<<brand<<endl;
        cout<<"Model: "<<model<<endl;
        cout<<"Rental Price per day: "<<rentalPrice<<endl;
        cout<<"Total Revenue Earned: "<<revenue<<endl;
    }

    void ShowRevenue() {
        cout<<"\nTotal Revenue Generated By "<<brand<<" "<<model<<": "<<revenue<<endl;
    }
    
};

int main(){
	
    Car c1(70,"Toyota", "GLI", 5000, true);

    c1.ShowInfo();
    
    c1.rentCar(6);
    c1.returnCar();
    
    c1.rentCar(11);
    c1.returnCar();
    
    c1.ShowRevenue();

    return 0;
}
